# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MysteriumVPN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MysteriumVPN

  target 'MysteriumVPNTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core', '~> 5.11.0'
  end

end
